services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - .:/app
      - composer:/composer
    depends_on:
      - db

  nginx:
    image: nginx:_NGINX_IMAGE_VERSION_
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - _NGINX_PORT_:80
    depends_on:
      - php

  # db:
  #   image: mariadb:_MYSQL_IMAGE_VERSION_
  #   volumes:
  #     - db:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
  #     MYSQL_USER: $DB_USERNAME
  #     MYSQL_PASSWORD: $DB_PASSWORD
  #     MYSQL_DATABASE: $DB_DATABASE
  #   ports:
  #     - _MYSQL_PORT_:3306

  # test-db:
  #   image: mariadb:_MYSQL_IMAGE_VERSION_
  #   volumes:
  #     - type: tmpfs
  #       target: /var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $DB_PASSWORD
  #     MYSQL_USER: $DB_USERNAME
  #     MYSQL_PASSWORD: $DB_PASSWORD
  #     MYSQL_DATABASE: $DB_DATABASE
  #   ports:
  #     - _MYSQL_TEST_PORT_:3306

  db:
    image: postgres:_POSTGRES_IMAGE_VERSION_
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - _POSTGRES_PORT_:5432

  test-db:
    image: postgres:_POSTGRES_IMAGE_VERSION_
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - _POSTGRES_TEST_PORT_:5432

  redis:
    image: redis:_REDIS_IMAGE_VERSION_
    volumes:
      - redis:/data
    ports:
      - _REDIS_PORT_:6379

volumes:
  db:
  composer:
    name: composer
    external: true
  redis:
